name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: hello_test
      id: hello_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: hello_test
        setup-command: sudo -H pip3 install pytest
        command: pytest hello_test.py
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO_TEST_RESULTS: "${{steps.hello_test.outputs.result}}"
      with:
        runners: hello_test
